installer is probably, hopefully (please god) done

diff --git a/gits-installer b/gits-installer
--- a/gits-installer
+++ b/gits-installer
@@ -4,7 +4,6 @@
 
 GH_URL="https://raw.githubusercontent.com/Jeff-Russ/gits/master/"
 
-
 # funcs _______________________________________________________________________
 
 exiterr () {
@@ -21,7 +20,6 @@ dir_found ()  { [ -d "$1" ] && return 0 || return 1; }
 file_found () { [ -f "$1" ] && return 0 || return 1; }
 str_eq () { [[ "$1" = "$2" ]] && return 0 || return 1; }
 is_z () { [[ -z "$1" ]] && return 0 || return 1; }
-
 
 #  ~/bin directory ____________________________________________________________
 
@@ -43,35 +41,45 @@ if not_in_path "$HOME/bin"; then
  else echo "~/bin was already added to PATH."
 fi
 
-HMBIN="$HOME/bin"
-cd "$HMBIN"
+cd "$HOME/bin"
 
-#  downloads __________________________________________________________________
-
+#  prep if --update ____________________________________________________________
 
 if str_eq "$1" "--update"; then 
-
 	tmp="$HOME/bin/gits_temp"
-
 	if dir_missing "$tmp"; then
-		mkdir "$tmp" || exiterr " mkdir ~bin/gits_temp failed."
-	fi
-
-	if file_found "$HMBIN/gits"; then 
-		mv "$HOME/bin/gits" "$tmp/gits" || exiterr " mv ~/bin/gits $dtmp/gits failed."
-	fi
-
-	if file_found "$HMBIN/GITS.1"; then 
-		mv "$HOME/bin/gits" "$tmp/gits" || exiterr " mv ~/bin/GITS.1 $dtmp/GITS.1 failed."
+		mkdir "$tmp" || exiterr "mkdir ~bin/gits_temp failed."
 	fi
 fi
 
+#  gits executable ____________________________________________________________
+
+if file_found "$HOME/bin/gits"; then 
+	if str_eq "$1" "--update"; then 
+		mv "$HOME/bin/gits" "$tmp/gits" || exiterr "mv ~/bin/gits $dtmp/gits failed."
+	else
+		exiterr "previous installation found. Run again with --update"
+	fi
+fi
 printf "downloading gits command executable... "
 curl -O "$GH_URL/gits" && echo "Done." || exiterr "curl -O $GH_URL/gits failed."
 chmod 755 "$HOME/bin/gits" || warning_mgs "unable to run 755 ~/bin/gits"
 
+
+#  man page ___________________________________________________________________
+
+if file_found "$HOME/bin/GITS.1"; then 
+	if str_eq "$1" "--update"; then 
+		mv "$HOME/bin/gits" "$tmp/gits" || exiterr "mv ~/bin/GITS.1 $dtmp/GITS.1 failed."
+	else
+		exiterr "previous installation found. Run again with --update"
+	fi
+fi
 printf "downloading man page... "
 curl -O "$GH_URL/GITS.1" && echo "Done." || exiterr "curl -O $GH_URL/GITS.1 failed."
+
+
+# cleanup if --update ____________________________________________________________
 
 if str_eq "$1" "--update"; then 
 	file_found "$HOME/bin/gits_temp/gits" && rm "$HOME/bin/gits_temp/gits"
